# Generated by Django 4.2.3 on 2023-07-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('category_description', models.CharField(max_length=150, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('product_description', models.CharField(max_length=150, verbose_name='Описание продукта')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_media/', verbose_name='Превью продукта')),
                ('product_category', models.CharField(max_length=150, verbose_name='Категория продукта')),
                ('product_price', models.IntegerField(default=0, verbose_name='Цена за покупку')),
                ('product_date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('product_date_modified', models.DateField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
